version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    environment:
      - ENV_VARIABLE=value
    networks:
      - app-network
      
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network